### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by sdsy888** [JiaxuanYou/P-GNN#15]
Hi, @JiaxuanYou 
Thank you for sharing your code.

When I tried to run  your code with `python main.py --model GCN --layer_num 3 --dataset grid
`, it gave such error:
```bash
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    out = model(data)
  File "/media/newhd/my_path/anaconda3/envs/pt1.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in
__call__
    result = self.forward(*input, **kwargs)
  File "/media/newhd/my_path/project/P-GNN/model.py", line 133, in forward
    x = self.conv_first(x, edge_index)
  File "/media/newhd/my_path/anaconda3/envs/pt1.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in
__call__
    result = self.forward(*input, **kwargs)
  File "/media/newhd/my_path/anaconda3/envs/pt1.0/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 99, in forward
    return self.propagate(edge_index, x=x, norm=norm)
  File "/media/newhd/my_path/anaconda3/envs/pt1.0/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 100, in propagate
    out = scatter_(self.aggr, out, edge_index[i], dim_size=size[i])
  File "/media/newhd/my_path/anaconda3/envs/pt1.0/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
    out = op(src, index, 0, None, dim_size, fill_value)
RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)
```

Seems like it has something to do with the `scatter_add` in `torch_geometric`. However, mine is `1.1.2` like yours.  ( I've also tried several other versions, none works）

So, do you have any idea how to solve this? Thank you again.

**Comment by sdsy888** [comment]
I just found that the problem is caused by the wrong `torch_geometric` version.

When I use the mentioned version `1.1.2` in the README, it will report the error above. But the newest version won't have any problem.
